const placeholders = {
  campaignPlaceholderImage: "/campaign_placeholder_image.webp",
  sampleCampaigns: [
        {
            id: 1,
            organization_id: 1,
            organization_name: "Alleanza Quartiere Vivo",
            signatures: 320,
            creator_id: 1,
            creator_first_name: "Giulia",
            creator_last_name: "Rossi",
            title: "Piu alberi lungo i viali scolastici",
            description: "Creiamo corridoi verdi e zone d'ombra davanti alle scuole per ridurre il calore urbano.",
            created_at: new Date(),
            cover_path: "",
            signature_goal: 600,
            is_public: true,
            comments_active: true,
            comments_require_approval: false,
            is_archived: false,
        },
        {
            id: 2,
            organization_id: null,
            organization_name: null,
            signatures: 89,
            creator_id: 2,
            creator_first_name: "Marco",
            creator_last_name: "Bianchi",
            title: "Panchine accessibili in centro",
            description: "Richiesta di nuove sedute ergonomiche con spazi adatti a carrozzine nelle piazze principali.",
            created_at: new Date(),
            cover_path: "",
            signature_goal: 250,
            is_public: true,
            comments_active: true,
            comments_require_approval: false,
            is_archived: false,
        },
        {
            id: 3,
            organization_id: 2,
            organization_name: "Mobilita Bene Comune",
            signatures: 540,
            creator_id: 3,
            creator_first_name: "Sara",
            creator_last_name: "Neri",
            title: "Corsia ciclabile continua nord-sud",
            description: "Un percorso sicuro che colleghi i quartieri periferici al centro senza interruzioni critiche.",
            created_at: new Date(),
            cover_path: "",
            signature_goal: 800,
            is_public: true,
            comments_active: true,
            comments_require_approval: true,
            is_archived: false,
        },
        {
            id: 4,
            organization_id: 3,
            organization_name: "Scuole Aperte",
            signatures: 74,
            creator_id: 4,
            creator_first_name: "Luca",
            creator_last_name: "Conti",
            title: "Biblioteca di quartiere aperta la sera",
            description: "Estensione degli orari fino alle 22 per supportare studenti lavoratori e studio condiviso.",
            created_at: new Date(),
            cover_path: "",
            signature_goal: 300,
            is_public: true,
            comments_active: true,
            comments_require_approval: false,
            is_archived: false,
        },
        {
            id: 5,
            organization_id: 4,
            organization_name: "Respira Citta",
            signatures: 412,
            creator_id: 5,
            creator_first_name: "Elena",
            creator_last_name: "Ferri",
            title: "Monitoraggio aria vicino alle scuole",
            description: "Installazione di sensori con dati pubblici in tempo reale per ridurre l'esposizione dei minori.",
            created_at: new Date(),
            cover_path: "",
            signature_goal: 700,
            is_public: true,
            comments_active: true,
            comments_require_approval: true,
            is_archived: false,
        },
        {
            id: 6,
            organization_id: null,
            organization_name: null,
            signatures: 190,
            creator_id: 6,
            creator_first_name: "Davide",
            creator_last_name: "Riva",
            title: "Attraversamenti rialzati zona stazione",
            description: "Interventi di moderazione del traffico nelle strade con maggiore incidentalita pedonale.",
            created_at: new Date(),
            cover_path: "",
            signature_goal: 400,
            is_public: true,
            comments_active: true,
            comments_require_approval: false,
            is_archived: false,
        },
    ]
} as const;

export type Branding = typeof placeholders;

export default placeholders;
